pipeline {
    agent any
      
    environment {
        //DockerHub credential
        registry = "anestm/maven-project"
        registryCredential ='docker'
        dockerImage = ''
    }
    stages {

        stage("clone repo") {
            steps {
                script {
                    // Let's clone the source
                    git branch:'anes' , url:'https://github.com/achrafchourabi/TimesheetWaves.git';
                }
            }
        }

        stage("mvn clean") {
            steps {
                script {
                    //this step attempts to clean the files and directories generated by Maven during its build
                    bat "mvn clean"
                }
            }
        }
        
        stage("mvn build") {
            steps {
                script {
            
                    bat "mvn package "
                }
            }
        }



        stage("Test stage") {
            steps {
                script {
                    // this step runs our JUnit tests through Maven
                    bat "mvn test"
                }
            }
        }

  	    stage("Sonar metrics") {
            steps {
                script {
                    // this step enable to execute the SonarQube analysis via a regular Maven goal
                    bat "mvn sonar:sonar "
                     }
                }
            } 
           
        stage("Deployment stage") {
            steps {
                script {
                 pom = readMavenPom file: "pom.xml";
                   echo "${pom.artifactId}-${pom.version}.${pom.packaging}"
                   bat "mvn deploy:deploy-file -DgroupId=${pom.groupId} -DartifactId=${pom.artifactId} -Dversion=${pom.version}  -DgeneratePom=true -Dpackaging=${pom.packaging}  -DrepositoryId=deploymentRepo -Durl=http://localhost:8081/repository/maven-releases/ -Dfile=target/${pom.artifactId}-${pom.version}.${pom.packaging}"
                }
            }
        }
     stage('Building docker image') {
          steps{
               script {
                 // this step build docker image 
                 docker.build registry + ":$BUILD_NUMBER"
                }
         }    
        }
       stage('Deploy Image to Dockerhub') {
         steps{
           script {
                 // this step push the docker image builded to dockerhub
                 docker.withRegistry( '', registryCredential ) {	
	         bat "docker push $registry:$BUILD_NUMBER"
                 }
          }
        }
      }

        stage('Remove Unused docker image') {
          steps{
                // this step delete the image to cleanup your server space after build and deploy
	        bat "docker rmi $registry:$BUILD_NUMBER"
            }
        }
          
    }
    
      post {  
      
         success {  
         mail bcc: '', body: '''success Jenkins pipline .
             Jenkins.''', cc: '', from: '', replyTo: '', subject: 'Build succed', to: 'anestemani00@gmail.com'   
         }  
         failure {  
             mail bcc: '', body: '''failed Jenkins pipline .
             Jenkins.''', cc: '', from: '', replyTo: '', subject: 'Build failed', to: 'anestemani00@gmail.com'   
         } 
      }
}